
import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { AppRoute, ChildProfile } from '../types';
import { supabase } from '../services/supabase';
import { ArrowRight, Check, Loader2, Camera, ArrowLeft } from 'lucide-react';

const ProfileSetup: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [existingCount, setExistingCount] = useState(0);
  const [hasExistingProfiles, setHasExistingProfiles] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  
  const [profile, setProfile] = useState<ChildProfile>({
    id: '', // Generated by DB or passed if editing
    name: '',
    age: 5,
    gender: 'boy',
    hairColor: 'brown',
    hairStyle: 'short',
    eyeColor: 'brown',
    skinTone: 'light',
    photoUrl: undefined
  });

  useEffect(() => {
    // Check if we are editing an existing profile
    if (location.state?.profile) {
        setProfile(location.state.profile);
        setIsEditing(true);
    }

    // Check local storage
    const stored = localStorage.getItem('child_profiles');
    if (stored && JSON.parse(stored).length > 0) {
        setHasExistingProfiles(true);
    }
    // Also Check DB immediately
    checkProfiles();
  }, [location.state]);

  const checkProfiles = async () => {
    try {
        const { count, error } = await supabase.from('child_profiles').select('*', { count: 'exact', head: true });
        if (error) throw error;
        
        setExistingCount(count || 0);
        if ((count || 0) > 0) {
            setHasExistingProfiles(true);
        }
        
        // Only restrict if creating NEW and limit reached (and not editing)
        if ((count || 0) >= 5 && !location.state?.profile) {
            alert("Você já atingiu o limite de 5 perfis.");
            navigate(AppRoute.HOME);
        }
    } catch (e) {
        console.warn("Could not check profiles", e);
    }
  };

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.size > 2 * 1024 * 1024) {
          alert("A foto é muito grande! Tente uma menor.");
          return;
      }
      const reader = new FileReader();
      reader.onload = (event) => {
        const src = event.target?.result as string;
        setProfile({ ...profile, photoUrl: src });
      };
      reader.readAsDataURL(file);
    }
  };

  // Helper function to generate SVG avatar string based on traits
  const generateAvatar = (p: ChildProfile): string => {
    const skinColors: Record<string, string> = { light: '#fde68a', medium: '#d4a373', dark: '#8d5524' };
    const hairColors: Record<string, string> = { blonde: '#fcd34d', brown: '#50301e', black: '#171717', red: '#ef4444' };
    
    const skin = skinColors[p.skinTone] || skinColors.light;
    const hair = hairColors[p.hairColor] || hairColors.brown;
    const bg = p.gender === 'girl' ? '#fce7f3' : '#e0f2fe'; 

    let hairSvg = '';
    // Enhanced Hair Styles
    if (p.hairStyle === 'short') {
        hairSvg = `
          <path d="M50 80 C50 40 150 40 150 80 L150 100 C150 90 140 85 130 85 C120 85 110 95 100 95 C90 95 80 85 70 85 C60 85 50 90 50 100 Z" fill="${hair}"/>
          <path d="M100 45 Q120 35 130 50" stroke="${hair}" stroke-width="4" fill="none" opacity="0.3"/>
        `;
    } else if (p.hairStyle === 'long') {
        hairSvg = `
          <path d="M50 80 C50 30 150 30 150 80 L150 160 C150 170 130 170 130 160 L130 110 L70 110 L70 160 C70 170 50 170 50 160 Z" fill="${hair}"/>
          <path d="M60 80 C60 100 60 160 60 160" stroke="${hair}" stroke-width="2" opacity="0.2"/>
          <path d="M140 80 C140 100 140 160 140 160" stroke="${hair}" stroke-width="2" opacity="0.2"/>
        `;
    } else if (p.hairStyle === 'curly') {
        hairSvg = `
          <circle cx="55" cy="80" r="15" fill="${hair}"/>
          <circle cx="145" cy="80" r="15" fill="${hair}"/>
          <circle cx="70" cy="65" r="15" fill="${hair}"/>
          <circle cx="130" cy="65" r="15" fill="${hair}"/>
          <circle cx="100" cy="55" r="18" fill="${hair}"/>
          <circle cx="85" cy="60" r="15" fill="${hair}"/>
          <circle cx="115" cy="60" r="15" fill="${hair}"/>
          <path d="M60 80 C60 130 140 130 140 80" fill="none"/>
        `;
    } else { // Straight/Generic
        hairSvg = `
          <path d="M50 80 C50 30 150 30 150 80 L150 120 L50 120 Z" fill="${hair}"/>
          <path d="M100 35 L100 55" stroke="rgba(0,0,0,0.1)" stroke-width="2"/>
        `;
    }

    const svgString = `
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
        <rect width="200" height="200" fill="${bg}"/>
        <!-- Back Hair (if long) -->
        ${p.hairStyle === 'long' ? `<path d="M60 90 L140 90 L145 160 L55 160 Z" fill="${hair}"/>` : ''}
        
        <!-- Face Shape -->
        <rect x="75" y="140" width="50" height="40" fill="${skin}"/> <!-- Neck -->
        <ellipse cx="100" cy="105" rx="55" ry="60" fill="${skin}"/>
        
        <!-- Ears -->
        <circle cx="45" cy="110" r="12" fill="${skin}"/>
        <circle cx="155" cy="110" r="12" fill="${skin}"/>
        
        <!-- Shirt -->
        <path d="M50 200 Q100 150 150 200" fill="${p.gender === 'girl' ? '#ec4899' : '#3b82f6'}"/>
        
        <!-- Facial Features -->
        <g fill="#1e293b">
           <!-- Eyes -->
           <circle cx="80" cy="105" r="7"/>
           <circle cx="120" cy="105" r="7"/>
           <!-- Eye Highlights -->
           <circle cx="82" cy="103" r="2" fill="white"/>
           <circle cx="122" cy="103" r="2" fill="white"/>
        </g>
        
        <!-- Blush -->
        <ellipse cx="70" cy="120" rx="8" ry="5" fill="#ef4444" opacity="0.2"/>
        <ellipse cx="130" cy="120" rx="8" ry="5" fill="#ef4444" opacity="0.2"/>

        <!-- Smile -->
        <path d="M85 130 Q100 145 115 130" stroke="#78350f" stroke-width="4" fill="none" stroke-linecap="round"/>
        
        <!-- Front Hair -->
        ${hairSvg}
      </svg>
    `;

    return `data:image/svg+xml;utf8,${encodeURIComponent(svgString.replace(/\n/g, '').trim())}`;
  };

  const handleSave = async () => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        throw new Error("Sessão expirou. Por favor, faça login novamente.");
      }

      const generatedAvatar = generateAvatar(profile);

      // Prepare payload
      const payload: any = {
          user_id: user.id,
          name: profile.name,
          age: profile.age,
          gender: profile.gender,
          hair_color: profile.hairColor,
          hair_style: profile.hairStyle,
          eye_color: profile.eyeColor,
          skin_tone: profile.skinTone,
          avatar_base: generatedAvatar,
          photo_url: profile.photoUrl
      };

      // If editing, include ID to trigger update
      if (isEditing && profile.id) {
          payload.id = profile.id;
      }

      const { data, error } = await supabase.from('child_profiles')
        .upsert(payload)
        .select().single();

      if (error) throw error;

      if (data) {
          const newProfile: ChildProfile = {
            id: data.id,
            name: data.name,
            age: data.age,
            gender: data.gender,
            hairColor: data.hair_color,
            hairStyle: data.hair_style,
            eyeColor: data.eye_color,
            skinTone: data.skin_tone,
            avatarBase: data.avatar_base,
            photoUrl: data.photo_url
          };
          
          localStorage.setItem('active_profile_id', newProfile.id);
          localStorage.setItem('child_profile', JSON.stringify(newProfile));
          
          // Update local list
          const storedList = localStorage.getItem('child_profiles');
          let list = storedList ? JSON.parse(storedList) : [];
          
          if (isEditing) {
              list = list.map((p: ChildProfile) => p.id === newProfile.id ? newProfile : p);
          } else {
              list.push(newProfile);
          }
          localStorage.setItem('child_profiles', JSON.stringify(list));

          navigate(AppRoute.HOME);
      }

    } catch (e: any) {
      console.error(e);
      alert(`Erro ao salvar perfil: ${e.message}`);
    } finally {
      setLoading(false);
    }
  };

  const renderStep1 = () => (
    <div className="space-y-6 animate-slide-up">
       <div className="text-center">
          <h2 className="text-3xl font-black text-slate-800">{isEditing ? 'Editar Perfil' : 'Novo Aventureiro'}</h2>
          {!isEditing && <p className="text-slate-400">Perfil {existingCount + 1} de 5</p>}
       </div>

       {/* Photo Upload */}
       <div className="flex flex-col items-center gap-4 mb-4">
          <input 
             type="file" 
             accept="image/*" 
             ref={fileInputRef} 
             className="hidden" 
             onChange={handlePhotoUpload} 
          />
          <button 
             onClick={() => fileInputRef.current?.click()}
             className="relative w-32 h-32 rounded-full bg-slate-100 border-4 border-white shadow-lg overflow-hidden flex items-center justify-center group active:scale-95 transition-transform"
          >
             {profile.photoUrl ? (
                <img src={profile.photoUrl} alt="Foto" className="w-full h-full object-cover" />
             ) : (
                <Camera size={40} className="text-slate-300 group-hover:text-blue-400 transition-colors" />
             )}
             <div className="absolute bottom-0 w-full bg-black/40 text-white text-[10px] py-1 text-center font-bold">
               {profile.photoUrl ? 'ALTERAR' : 'FOTO'}
             </div>
          </button>
          <span className="text-xs text-slate-400">Toque para adicionar uma foto real</span>
       </div>

       <div className="bg-white p-6 rounded-3xl border-2 border-slate-100 shadow-sm">
          <label className="block text-sm font-bold text-slate-400 uppercase tracking-wide mb-2">Nome da Criança</label>
          <input 
            type="text" 
            value={profile.name}
            onChange={(e) => setProfile({...profile, name: e.target.value})}
            className="w-full text-3xl font-black text-slate-800 border-b-2 border-slate-200 focus:border-blue-500 outline-none py-2 placeholder-slate-200"
            placeholder="Ex: Miguel"
            autoFocus
          />
       </div>

       <div className="bg-white p-6 rounded-3xl border-2 border-slate-100 shadow-sm">
          <label className="block text-sm font-bold text-slate-400 uppercase tracking-wide mb-4">Quantos anos?</label>
          <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">
            {[3,4,5,6,7,8,9,10].map(age => (
               <button 
                 key={age}
                 onClick={() => setProfile({...profile, age})}
                 className={`w-14 h-14 rounded-2xl font-black text-xl flex-shrink-0 border-2 transition-all
                   ${profile.age === age ? 'bg-blue-500 text-white border-blue-600 scale-110' : 'bg-slate-50 text-slate-400 border-slate-200'}
                 `}
               >
                 {age}
               </button>
            ))}
          </div>
       </div>
       
       <div className="flex gap-4">
          <button 
             onClick={() => setProfile({...profile, gender: 'boy'})}
             className={`flex-1 py-4 rounded-2xl font-bold border-2 transition-all ${profile.gender === 'boy' ? 'bg-blue-100 border-blue-400 text-blue-700' : 'bg-white border-slate-100 text-slate-400'}`}
          >
             Menino 👦
          </button>
          <button 
             onClick={() => setProfile({...profile, gender: 'girl'})}
             className={`flex-1 py-4 rounded-2xl font-bold border-2 transition-all ${profile.gender === 'girl' ? 'bg-pink-100 border-pink-400 text-pink-700' : 'bg-white border-slate-100 text-slate-400'}`}
          >
             Menina 👧
          </button>
       </div>

       <button 
         disabled={!profile.name}
         onClick={() => setStep(2)}
         className="w-full py-4 bg-blue-500 disabled:bg-slate-300 text-white rounded-2xl font-black text-xl shadow-lg shadow-blue-200 mt-8 flex items-center justify-center gap-2"
       >
         PRÓXIMO <ArrowRight />
       </button>
    </div>
  );

  const renderStep2 = () => {
    const previewAvatar = generateAvatar(profile);

    return (
      <div className="space-y-6 animate-slide-up">
         <div className="text-center">
            <h2 className="text-3xl font-black text-slate-800">Personagem</h2>
            <p className="text-slate-400">Monte seu avatar digital!</p>
         </div>

         {/* LIVE PREVIEW */}
         <div className="flex justify-center -my-2">
            <div className="w-32 h-32 rounded-full border-4 border-white shadow-xl overflow-hidden bg-slate-100">
                <img src={previewAvatar} alt="Preview" className="w-full h-full object-cover" />
            </div>
         </div>

         {/* Hair Color */}
         <div className="bg-white p-5 rounded-3xl border border-slate-100">
            <label className="text-xs font-bold text-slate-400 uppercase block mb-3">Cor do Cabelo</label>
            <div className="flex gap-3 justify-center">
               {['blonde', 'brown', 'black', 'red'].map(c => (
                  <button 
                    key={c} 
                    onClick={() => setProfile({...profile, hairColor: c})}
                    className={`w-12 h-12 rounded-full border-4 shadow-sm transition-transform ${profile.hairColor === c ? 'border-blue-500 scale-110' : 'border-white'}`}
                    style={{ backgroundColor: c === 'blonde' ? '#fcd34d' : c === 'brown' ? '#50301e' : c === 'black' ? '#171717' : '#ef4444' }}
                  />
               ))}
            </div>
         </div>

         {/* Hair Style */}
         <div className="bg-white p-5 rounded-3xl border border-slate-100">
            <label className="text-xs font-bold text-slate-400 uppercase block mb-3">Estilo do Cabelo</label>
            <div className="grid grid-cols-2 gap-2">
               {['short', 'long', 'curly', 'straight'].map(s => (
                  <button 
                    key={s} 
                    onClick={() => setProfile({...profile, hairStyle: s})}
                    className={`py-2 px-4 rounded-xl text-sm font-bold border-2 ${profile.hairStyle === s ? 'bg-blue-50 border-blue-400 text-blue-700' : 'bg-slate-50 border-slate-100 text-slate-400'}`}
                  >
                    {s === 'short' ? 'Curto' : s === 'long' ? 'Longo' : s === 'curly' ? 'Cacheado' : 'Liso'}
                  </button>
               ))}
            </div>
         </div>

         {/* Skin Tone */}
         <div className="bg-white p-5 rounded-3xl border border-slate-100">
            <label className="text-xs font-bold text-slate-400 uppercase block mb-3">Tom de Pele</label>
            <div className="flex gap-3 justify-center">
               {['light', 'medium', 'dark'].map(s => (
                  <button 
                    key={s} 
                    onClick={() => setProfile({...profile, skinTone: s})}
                    className={`w-12 h-12 rounded-full border-4 shadow-sm transition-transform ${profile.skinTone === s ? 'border-blue-500 scale-110' : 'border-white'}`}
                    style={{ backgroundColor: s === 'light' ? '#fde68a' : s === 'medium' ? '#d4a373' : '#8d5524' }}
                  />
               ))}
            </div>
         </div>

         <button 
           onClick={handleSave}
           disabled={loading}
           className="w-full py-4 bg-green-500 text-white rounded-2xl font-black text-xl shadow-lg shadow-green-200 mt-4 flex items-center justify-center gap-2 disabled:opacity-70"
         >
           {loading ? <Loader2 className="animate-spin" /> : <><Check /> PRONTO!</>}
         </button>
      </div>
    );
  };

  return (
    <div className="h-full bg-slate-50 p-6 flex flex-col pt-12 overflow-y-auto relative">
       {/* Navigation Button */}
       <div className="absolute top-4 left-4 z-20">
          {step === 2 && (
             <button onClick={() => setStep(1)} className="w-10 h-10 bg-white rounded-full border border-slate-200 flex items-center justify-center text-slate-500 shadow-sm active:scale-95">
               <ArrowLeft size={20} />
             </button>
          )}
          {step === 1 && hasExistingProfiles && (
             <button onClick={() => navigate(AppRoute.HOME)} className="w-10 h-10 bg-white rounded-full border border-slate-200 flex items-center justify-center text-slate-500 shadow-sm active:scale-95">
               <ArrowLeft size={20} />
             </button>
          )}
       </div>

       {step === 1 ? renderStep1() : renderStep2()}
    </div>
  );
};

export default ProfileSetup;
