import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppRoute, ChildProfile } from '../types';
import { supabase } from '../services/supabase';
import { ArrowRight, Check, Loader2 } from 'lucide-react';

const ProfileSetup: React.FC = () => {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [existingCount, setExistingCount] = useState(0);
  
  const [profile, setProfile] = useState<ChildProfile>({
    id: '', // Generated by DB
    name: '',
    age: 5,
    gender: 'boy',
    hairColor: 'brown',
    hairStyle: 'short',
    eyeColor: 'brown',
    skinTone: 'light',
  });

  useEffect(() => {
    checkProfiles();
  }, []);

  const checkProfiles = async () => {
    const { count } = await supabase.from('child_profiles').select('*', { count: 'exact', head: true });
    setExistingCount(count || 0);
    if ((count || 0) >= 5) {
        alert("Você já atingiu o limite de 5 perfis.");
        navigate(AppRoute.HOME);
    }
  };

  // Helper function to generate SVG avatar string based on traits
  const generateAvatar = (p: ChildProfile): string => {
    const skinColors: Record<string, string> = { light: '#fde68a', medium: '#d4a373', dark: '#5c3a21' };
    const hairColors: Record<string, string> = { blonde: '#fcd34d', brown: '#78350f', black: '#171717', red: '#ef4444' };
    
    const skin = skinColors[p.skinTone] || skinColors.light;
    const hair = hairColors[p.hairColor] || hairColors.brown;
    const bg = p.gender === 'girl' ? '#fce7f3' : '#e0f2fe'; // pink-100 or sky-100

    // Hair Path Logic (Simplified)
    let hairSvg = '';
    if (p.hairStyle === 'short') {
        hairSvg = `<path d="M70 60 C70 30 130 30 130 60 L130 90 C130 80 120 70 100 70 C80 70 70 80 70 90 Z" fill="${hair}"/>`; // Top crop
    } else if (p.hairStyle === 'long') {
        hairSvg = `<path d="M60 60 C60 20 140 20 140 60 L140 140 C140 150 120 150 120 140 L120 100 L80 100 L80 140 C80 150 60 150 60 140 Z" fill="${hair}"/>`;
    } else if (p.hairStyle === 'curly') {
        hairSvg = `<path d="M65 60 C60 40 80 20 100 25 C120 20 140 40 135 60 C145 70 145 90 135 100 C135 120 115 130 100 125 C85 130 65 120 65 100 C55 90 55 70 65 60 Z" fill="${hair}"/>`;
    } else {
        // Straight/Default
        hairSvg = `<path d="M65 60 C65 20 135 20 135 60 L135 120 L65 120 Z" fill="${hair}"/>`;
    }

    const svgString = `
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
        <rect width="200" height="200" fill="${bg}"/>
        <!-- Hair Back (for long hair) -->
        ${p.hairStyle === 'long' ? `<path d="M70 80 L130 80 L130 150 L70 150 Z" fill="${hair}"/>` : ''}
        <!-- Neck -->
        <rect x="85" y="140" width="30" height="40" fill="${skin}"/>
        <!-- Shirt -->
        <path d="M50 200 Q100 160 150 200" fill="${p.gender === 'girl' ? '#f472b6' : '#60a5fa'}"/>
        <!-- Face -->
        <circle cx="100" cy="100" r="45" fill="${skin}"/>
        <!-- Eyes -->
        <circle cx="85" cy="95" r="5" fill="#1e293b"/>
        <circle cx="115" cy="95" r="5" fill="#1e293b"/>
        <!-- Smile -->
        <path d="M90 120 Q100 130 110 120" stroke="#78350f" stroke-width="3" fill="none"/>
        <!-- Hair Front -->
        ${hairSvg}
      </svg>
    `;

    return `data:image/svg+xml;utf8,${encodeURIComponent(svgString.replace(/\n/g, '').trim())}`;
  };

  const handleSave = async () => {
    setLoading(true);
    try {
      // FIX: Use getUser() to ensure we have the correct user object
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        throw new Error("Sessão expirou. Por favor, faça login novamente.");
      }

      // Generate visual avatar
      const generatedAvatar = generateAvatar(profile);

      // Insert into Supabase
      const { data, error } = await supabase.from('child_profiles').insert({
          user_id: user.id,
          name: profile.name,
          age: profile.age,
          gender: profile.gender,
          hair_color: profile.hairColor,
          hair_style: profile.hairStyle,
          eye_color: profile.eyeColor,
          skin_tone: profile.skinTone,
          avatar_base: generatedAvatar // Save the generated SVG
      }).select().single();

      if (error) throw error;

      if (data) {
          // Set Active in Local Storage for Session
          const newProfile: ChildProfile = {
            id: data.id,
            name: data.name,
            age: data.age,
            gender: data.gender,
            hairColor: data.hair_color,
            hairStyle: data.hair_style,
            eyeColor: data.eye_color,
            skinTone: data.skin_tone,
            avatarBase: data.avatar_base
          };
          
          // Update Local Cache for instant access
          localStorage.setItem('active_profile_id', newProfile.id);
          
          // Append to local list cache
          const storedList = localStorage.getItem('child_profiles');
          const list = storedList ? JSON.parse(storedList) : [];
          list.push(newProfile);
          localStorage.setItem('child_profiles', JSON.stringify(list));

          navigate(AppRoute.HOME);
      }

    } catch (e: any) {
      console.error(e);
      alert(`Erro ao salvar perfil: ${e.message}`);
    } finally {
      setLoading(false);
    }
  };

  const renderStep1 = () => (
    <div className="space-y-6 animate-slide-up">
       <div className="text-center">
          <h2 className="text-3xl font-black text-slate-800">Novo Aventureiro</h2>
          <p className="text-slate-400">Perfil {existingCount + 1} de 5</p>
       </div>

       <div className="bg-white p-6 rounded-3xl border-2 border-slate-100 shadow-sm">
          <label className="block text-sm font-bold text-slate-400 uppercase tracking-wide mb-2">Nome da Criança</label>
          <input 
            type="text" 
            value={profile.name}
            onChange={(e) => setProfile({...profile, name: e.target.value})}
            className="w-full text-3xl font-black text-slate-800 border-b-2 border-slate-200 focus:border-blue-500 outline-none py-2 placeholder-slate-200"
            placeholder="Ex: Miguel"
            autoFocus
          />
       </div>

       <div className="bg-white p-6 rounded-3xl border-2 border-slate-100 shadow-sm">
          <label className="block text-sm font-bold text-slate-400 uppercase tracking-wide mb-4">Quantos anos?</label>
          <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">
            {[3,4,5,6,7,8,9,10].map(age => (
               <button 
                 key={age}
                 onClick={() => setProfile({...profile, age})}
                 className={`w-14 h-14 rounded-2xl font-black text-xl flex-shrink-0 border-2 transition-all
                   ${profile.age === age ? 'bg-blue-500 text-white border-blue-600 scale-110' : 'bg-slate-50 text-slate-400 border-slate-200'}
                 `}
               >
                 {age}
               </button>
            ))}
          </div>
       </div>
       
       <div className="flex gap-4">
          <button 
             onClick={() => setProfile({...profile, gender: 'boy'})}
             className={`flex-1 py-4 rounded-2xl font-bold border-2 transition-all ${profile.gender === 'boy' ? 'bg-blue-100 border-blue-400 text-blue-700' : 'bg-white border-slate-100 text-slate-400'}`}
          >
             Menino 👦
          </button>
          <button 
             onClick={() => setProfile({...profile, gender: 'girl'})}
             className={`flex-1 py-4 rounded-2xl font-bold border-2 transition-all ${profile.gender === 'girl' ? 'bg-pink-100 border-pink-400 text-pink-700' : 'bg-white border-slate-100 text-slate-400'}`}
          >
             Menina 👧
          </button>
       </div>

       <button 
         disabled={!profile.name}
         onClick={() => setStep(2)}
         className="w-full py-4 bg-blue-500 disabled:bg-slate-300 text-white rounded-2xl font-black text-xl shadow-lg shadow-blue-200 mt-8 flex items-center justify-center gap-2"
       >
         PRÓXIMO <ArrowRight />
       </button>
    </div>
  );

  const renderStep2 = () => {
    // Preview Avatar
    const previewAvatar = generateAvatar(profile);

    return (
      <div className="space-y-6 animate-slide-up">
         <div className="text-center">
            <h2 className="text-3xl font-black text-slate-800">Como você é?</h2>
            <p className="text-slate-400">Monte seu personagem!</p>
         </div>

         {/* LIVE PREVIEW */}
         <div className="flex justify-center -my-2">
            <div className="w-32 h-32 rounded-full border-4 border-white shadow-xl overflow-hidden bg-slate-100">
                <img src={previewAvatar} alt="Preview" className="w-full h-full object-cover" />
            </div>
         </div>

         {/* Hair Color */}
         <div className="bg-white p-5 rounded-3xl border border-slate-100">
            <label className="text-xs font-bold text-slate-400 uppercase block mb-3">Cor do Cabelo</label>
            <div className="flex gap-3 justify-center">
               {['blonde', 'brown', 'black', 'red'].map(c => (
                  <button 
                    key={c} 
                    onClick={() => setProfile({...profile, hairColor: c})}
                    className={`w-12 h-12 rounded-full border-4 shadow-sm transition-transform ${profile.hairColor === c ? 'border-blue-500 scale-110' : 'border-white'}`}
                    style={{ backgroundColor: c === 'blonde' ? '#fcd34d' : c === 'brown' ? '#78350f' : c === 'black' ? '#171717' : '#ef4444' }}
                  />
               ))}
            </div>
         </div>

         {/* Hair Style */}
         <div className="bg-white p-5 rounded-3xl border border-slate-100">
            <label className="text-xs font-bold text-slate-400 uppercase block mb-3">Estilo do Cabelo</label>
            <div className="grid grid-cols-2 gap-2">
               {['short', 'long', 'curly', 'straight'].map(s => (
                  <button 
                    key={s} 
                    onClick={() => setProfile({...profile, hairStyle: s})}
                    className={`py-2 px-4 rounded-xl text-sm font-bold border-2 ${profile.hairStyle === s ? 'bg-blue-50 border-blue-400 text-blue-700' : 'bg-slate-50 border-slate-100 text-slate-400'}`}
                  >
                    {s === 'short' ? 'Curto' : s === 'long' ? 'Longo' : s === 'curly' ? 'Cacheado' : 'Liso'}
                  </button>
               ))}
            </div>
         </div>

         {/* Skin Tone */}
         <div className="bg-white p-5 rounded-3xl border border-slate-100">
            <label className="text-xs font-bold text-slate-400 uppercase block mb-3">Tom de Pele</label>
            <div className="flex gap-3 justify-center">
               {['light', 'medium', 'dark'].map(s => (
                  <button 
                    key={s} 
                    onClick={() => setProfile({...profile, skinTone: s})}
                    className={`w-12 h-12 rounded-full border-4 shadow-sm transition-transform ${profile.skinTone === s ? 'border-blue-500 scale-110' : 'border-white'}`}
                    style={{ backgroundColor: s === 'light' ? '#fde68a' : s === 'medium' ? '#d4a373' : '#5c3a21' }}
                  />
               ))}
            </div>
         </div>

         <button 
           onClick={handleSave}
           disabled={loading}
           className="w-full py-4 bg-green-500 text-white rounded-2xl font-black text-xl shadow-lg shadow-green-200 mt-4 flex items-center justify-center gap-2 disabled:opacity-70"
         >
           {loading ? <Loader2 className="animate-spin" /> : <><Check /> PRONTO!</>}
         </button>
      </div>
    );
  };

  return (
    <div className="h-full bg-slate-50 p-6 flex flex-col pt-12 overflow-y-auto">
       {step === 1 ? renderStep1() : renderStep2()}
    </div>
  );
};

export default ProfileSetup;